TOPLEVEL_LANG = verilog
VERILOG_SOURCES = $(shell pwd)/comparador_nbits.v
TOPLEVEL = comparador_nbits
MODULE = comparador_nbits_tb
WAVES = 1

SIM = icarus

include $(shell cocotb-config --makefiles)/Makefile.sim
