TOPLEVEL_LANG = verilog
VERILOG_SOURCES = $(shell pwd)/contador_universal.v
TOPLEVEL = contador_universal
MODULE = contador_universal_tb
WAVES = 1

SIM = icarus

include $(shell cocotb-config --makefiles)/Makefile.sim
